# frozen_string_literal: true
source "https://rubygems.org"

gem "rspec"
gem "rake"
gem "safe_ruby"
gem "rubocop", '0.52.0'
gem 'mastery_answer_code_quality', :git => 'https://github.com/makersacademy/mastery_answer_code_quality.git'
